vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        pizza:
            uri_prefix: /images/pizza
            upload_destination: '%kernel.project_dir%/public/images/pizza'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
