version: '3'
services:
  php:
    container_name: php-app-pizza
    build: php8Sf6
    volumes:
      - .:/var/www/TheBestPizza

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: BestPizza
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
volumes:
  db-data: